spring:
  application:
    name: studyroom
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET_KEY}
  # 시간대 설정
  jackson:
    time-zone: Asia/Seoul

# JVM 시간대 설정
server:
  timezone: Asia/Seoul

logging:
  level:
    org.springframework.web.reactive.function.server: DEBUG
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: DEBUG
    com.jvc.studyroom.domain.studySession: DEBUG  # 세션 관련 디버그 로그