spring:
  application:
    name: studyroom
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET_KEY}
  # 시간대 설정
  jackson:
    time-zone: Asia/Seoul

# JVM 시간대 설정
server:
  timezone: Asia/Seoul

logging:
  level:
    org.springframework.web.reactive.function.server: DEBUG
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: DEBUG
    com.jvc.studyroom.domain.studySession: DEBUG  # 세션 관련 디버그 로그
