spring:
  application:
    name: studyroom

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org.springframework.web.reactive.function.server: DEBUG
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: DEBUG